name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branchâ€™s name
  push:
    branches: [master]
    paths:
      - "assets/**"
      - "CHANGELOG.md"
      - "CONTRIBUTING.md"
  workflow_dispatch:

jobs:
  repo_dispatch:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.DOCS_TRIGGER_TOKEN }}
        name: test
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rmpc-org/rmpc-org.github.io/dispatches \
            -d '{"event_type":"docs_update","client_payload":{}}'
